### ISSUE TITLE
Custom templates need underscore.string

### ISSUE THREAD

**Issue by DaftMonk** [DaftMonk/generator-ng-component#25]
Breaking change with 0.1.1:

By upgrading the yeoman generator, we no longer expose underscore.String as `this._` for templates, causing an error when generating files from custom templates.

```
(!) #_ is deprecated. Require your own version of Lodash or underscore.string
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Cannot read property 'dasherize' of undefined
    at eval (lodash.templateSources[1]:9:12)
    at underscore (/usr/local/lib/node_modules/generator-ng-component/node_modules/yeoman-generator/lib/util/engines.js:23:45)
    at Generator.actions.engine (/usr/local/lib/node_modules/generator-ng-component/node_modules/yeoman-generator/lib/actions/actions.js:224:32)
    at Generator.template (/usr/local/lib/node_modules/generator-ng-component/node_modules/yeoman-generator/lib/actions/actions.js:198:19)
    at /usr/local/lib/node_modules/generator-ng-component/util.js:121:14
    at Array.forEach (native)
    at Object.copyTemplates (/usr/local/lib/node_modules/generator-ng-component/util.js:114:6)
    at Generator.createFiles [as writing] (/usr/local/lib/node_modules/generator-ng-component/route/index.js:41:10)
    at /usr/local/lib/node_modules/generator-ng-component/node_modules/yeoman-generator/lib/base.js:421:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by kingcody** [comment]
Part of the problem is that when `yeoman-generator` [deprecated lodash](https://github.com/yeoman/generator/commit/803d2cd487cb8f845b1c8284f62198f835a3d0ae) they didn't define the property as `configurable: true` (making it read only); so this isn't something we can monkey-patch. I made lodash (extended with underscore.string) available via `this.lodash` as part of the upgrade.

Perhaps a good solution would be to roll back the breaking changes and release `0.1.2`. Then reapply and release `0.2.0` with a note about lodash moving and how to upgrade.

**Comment by kingcody** [comment]
@DaftMonk if that sound like a good idea, here is a [`release/v0.1.2`](https://github.com/DaftMonk/generator-ng-component/tree/release/v0.1.2) branch that has been checked out pre `yeoman-generator >= 0.19.0`. I've update the change log to be historically correct and patch bumped `package.json`.

**Comment by Awk34** [comment]
Since it's a breaking change, it should be a `1.0.0` release instead of `0.2.0`, yes?

**Comment by kingcody** [comment]
@Awk34 that is correct per semver. However a `1.0.0` release carries a lot of weight for some people. Also, not to join the bandwagon or anything but, `yeoman-generator` has been making breaking changes in minor versions recently as well.

**Comment by Awk34** [comment]
I think we should stick to semver
