### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by manmon42** [DaftMonk/generator-ng-component#51]
Hey, so when I try and run any of the sub-generators from generator-angular-fullstack I get.
`TypeError: Cannot read property 'indexOf' of undefined`

Here's the full stacktrace.
```
D:\Desktop\whenDoesItEnd>yo angular-fullstack:route switch
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'indexOf' of undefined
    at Generator.hasExtension (D:\Desktop\whenDoesItEnd\node_modules\generator-ng-component\generators\script-base.js:45:28)
    at Generator.exports.default (D:\Desktop\whenDoesItEnd\node_modules\generator-ng-component\generators\script-base.js:48:25)
    at Generator.initializing (D:\Desktop\whenDoesItEnd\node_modules\generator-ng-component\generators\route\index.js:37:35)
    at Object.<anonymous> (D:\Desktop\whenDoesItEnd\node_modules\generator-ng-component\node_modules\yeoman-generator\lib\base.js:431:23)
    at D:\Desktop\whenDoesItEnd\node_modules\run-async\index.js:26:25
    at D:\Desktop\whenDoesItEnd\node_modules\run-async\index.js:25:19
    at D:\Desktop\whenDoesItEnd\node_modules\generator-ng-component\node_modules\yeoman-generator\lib\base.js:432:9
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by Awk34** [comment]
@manmon42 can you post your `.yo-rc.json`?

**Comment by jeremywhittington** [comment]
I am getting the same error on Windows 10 64-bit.

> npm -v
4.1.1

> yo --version
1.8.5

> npm list -g generator-angular-fullstack
generator-angular-fullstack@5.0.0-alpha.4

>gulp --v
[03:06:40] Requiring external module babel-register
[03:06:40] CLI version 1.2.2
[03:06:40] Local version 3.9.1

[.yo-rc.json.txt](https://github.com/DaftMonk/generator-ng-component/files/705850/default.yo-rc.json.txt)

**Comment by Awk34** [comment]
@jeremywhittington generator-angular-fullstack@5.0.0-alpha.4 does not support subgenerators yet
